# Generated by Django 5.0.4 on 2026-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_classroom_teacher_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'grade_level', 'room_no'], name='idx_classroom_school_grade'),
        ),
    ]
