# Generated by Django 5.0.4 on 2026-08-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_classroom_idx_classroom_school_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(related_name='teachers', to='apis.classroom'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['first_name', 'last_name'], name='idx_teacher_first_last__name'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='apis.classroom'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='idx_student_first_last_name'),
        ),
    ]
